/*
 * @文件描述:
 * @公司: 广电信通
 * @作者: 赵婷婷
 * @Date: 2020-11-23 11:16:15
 * @LastEditors: 赵婷婷
 * @LastEditTime: 2020-11-23 11:16:15
 */

export const mockGridsInfo = [
  {
    id: '7',
    aeskey: '87c8715c522954bd4beb3d25f4d52f2a',
    weight: '4',
    tag: '19bcc380867f2ca7472aa6fb288d7996',
    name: '文稿',
    enter: 'toDraftHome',
    isnav: '1',
    is_pc_nav: '1',
    version: '2.0.62',
    isphone: '1',
    baseurl: 'http://article.shandian.design',
    indexfunc: 'index',
    download:
      'http://fugui.shandian.design//public/2020/11/07/740338fdd88b41b0235709ffe32866be.zip',
    scheme: 'draft',
    icon: 'https://shandianyun.iqilu.com/home-logo/draft.png',
    color: 'null',
    quick: [
      {
        name: '新建文本',
        icon: 'shortcut_draft_text',
        path: 'toNewText',
      },
      {
        name: '新建视频',
        icon: 'shortcut_draft_video',
        path: 'toNewVideo',
      },
    ],
    opentype: '1',
    open_url: 'null',
    pc_weight: '1',
  },
  {
    id: '5',
    aeskey: '87c8715c522954bd4beb3d25f4d52f2a',
    weight: '2',
    tag: '597fcfd10a9986e546899755310ee82c',
    name: '线索',
    enter: 'toClueCenter',
    isnav: '1',
    is_pc_nav: '1',
    version: '2.0.1',
    isphone: '1',
    baseurl: 'http://clue.shandian.design',
    indexfunc: 'index',
    download:
      'http://fugui.shandian.design//public/2020/08/14/a3a5e58828b0fd8e42759d51e305cbcb.zip',
    scheme: 'clue',
    icon: 'https://shandianyun.iqilu.com/home-logo/clue.png',
    color: 'null',
    quick: [
      {
        name: '报线索',
        icon: 'shortcut_clue',
        path: 'toClueAdd',
        priv_id: 2,
      },
    ],
    opentype: '1',
    open_url: 'null',
    pc_weight: '2',
  },
  {
    id: '2',
    aeskey: '87c8715c522954bd4beb3d25f4d52f2a',
    weight: '3',
    tag: '57d6eb9dd26f620e358e1995dbd1cc4f',
    name: '选题',
    enter: 'allTopicList',
    isnav: '1',
    is_pc_nav: '1',
    version: '0.8.8',
    isphone: '1',
    baseurl: 'http://task.shandian.design',
    indexfunc: 'index',
    download:
      'http://fugui.shandian.design//public/2020/11/17/7604bf4b30dfad664b80738d3f12c641.zip',
    scheme: 'topic',
    icon: 'https://shandianyun.iqilu.com/home-logo/task.png',
    color: 'null',
    quick: [
      {
        name: '上报选题',
        icon: 'shortcut_topic_report',
        path: 'report',
        priv_id: 3,
      },
      {
        name: '派发选题',
        icon: 'shortcut_topic_distribute',
        path: 'distribute',
        priv_id: 4,
      },
    ],
    opentype: '1',
    open_url: 'null',
    pc_weight: '3',
  },
  {
    id: '1',
    aeskey: '87c8715c522954bd4beb3d25f4d52f2a',
    weight: '1',
    tag: 'ef63713b81581a41c80789ae72cca3be',
    name: '通联',
    enter: 'toTongLianList',
    isnav: '1',
    is_pc_nav: '1',
    version: '1.6.3',
    isphone: '1',
    baseurl: 'https://tonglian.shandian.design',
    indexfunc: '',
    download:
      'http://fugui.shandian.design//public/2020/11/06/4e77edeb11db48baf4301f24fbad6e00.zip',
    scheme: 'tonglian',
    icon: 'https://shandianyun.iqilu.com/home-logo/tonglian.png',
    color: 'null',
    quick: [
      {
        name: '发布通联',
        icon: 'shortcut_tonglian',
        path: 'toNewManuscript',
        priv_id: '111',
      },
    ],
    opentype: '1',
    open_url: 'null',
    pc_weight: '4',
  },
  {
    id: '9',
    aeskey: '87c8715c522954bd4beb3d25f4d52f2a',
    weight: '0',
    tag: '6dacfd3b50fccac865a92c01efee30c8',
    name: '公告通知',
    enter: '',
    isnav: '0',
    is_pc_nav: '1',
    version: '1.0.0',
    isphone: '1',
    baseurl: 'http://im.shandian.design',
    indexfunc: 'index',
    download: '',
    scheme: 'notice',
    icon: 'https://user.shandian.design/home-logo/xiao-xi-tong-zhi.png',
    color: '',
    quick: [
      {
        name: '发送通知',
        icon: 'shortcut_notice',
        path: 'addnotice',
        priv_id: 2,
      },
    ],
    opentype: '1',
    open_url: 'null',
    pc_weight: '6',
  },
  {
    id: '10',
    aeskey: '87c8715c522954bd4beb3d25f4d52f2a',
    weight: '0',
    tag: '09d4064fff60f5da7ef9b64c9abcdec0',
    name: '素材库',
    enter: '',
    isnav: '0',
    is_pc_nav: '1',
    version: '1.0.0',
    isphone: '0',
    baseurl: 'http://sucai.shandian.design',
    indexfunc: '',
    download: 'http://fugui.shandian.design/public/2019/08/09/8de4cd0630126b0e12a8db5e5dfc1122.zip',
    scheme: 'sucai',
    icon: 'https://shandianyun.iqilu.com/home-logo/sucai.png',
    color: null,
    quick: [],
    opentype: '1',
    open_url: null,
    pc_weight: '7',
  },
  {
    id: '11',
    aeskey: '87c8715c522954bd4beb3d25f4d52f2a',
    weight: '0',
    tag: 'b180ca9ab1f596f8f1425930f4ceed5a',
    name: '直播',
    enter: '',
    isnav: '0',
    is_pc_nav: '1',
    version: '1.0.1',
    isphone: '0',
    baseurl: 'superlive.iqilu.com:8081',
    indexfunc: '',
    download: 'http://fugui.shandian.design/public/2019/08/10/30e1d4c19df58446f73267b42f81ae4c.zip',
    scheme: 'superlive',
    icon: 'https://shandianyun.iqilu.com/home-logo/superlive.png',
    color: null,
    quick: [],
    opentype: '1',
    open_url: null,
    pc_weight: '8',
  },
  {
    id: '12',
    aeskey: '87c8715c522954bd4beb3d25f4d52f2a',
    weight: '5',
    tag: 'e5b1261af93bbb957526aa62855a4f43',
    name: '串联单',
    enter: 'goSeriesHomePage',
    isnav: '1',
    is_pc_nav: '1',
    version: '1.1.78',
    isphone: '1',
    baseurl: 'http://series.shandian.design',
    indexfunc: 'index',
    download:
      'http://fugui.shandian.design//public/2020/09/07/4085d24ee6b25837f1f5d654f794e7e9.zip',
    scheme: 'series',
    icon: 'https://shandianyun.iqilu.com/home-logo/series.png',
    color: 'null',
    quick: [],
    opentype: '1',
    open_url: 'null',
    pc_weight: '9',
  },
  {
    id: '14',
    aeskey: '87c8715c522954bd4beb3d25f4d52f2a',
    weight: '0',
    tag: 'dd967c6a1e94ae5c6440b76265a9ed9e',
    name: '系统设置',
    enter: '',
    isnav: '0',
    is_pc_nav: '1',
    version: '1.0.0',
    isphone: '0',
    baseurl: 'http://config.shandian.design',
    indexfunc: 'index',
    download: '',
    scheme: 'system_config',
    icon: 'https://shandianyun.iqilu.com/home-logo/system_config.png',
    color: null,
    quick: [],
    opentype: '1',
    open_url: null,
    pc_weight: '10',
  },
  {
    id: '15',
    aeskey: '87c8715c522954bd4beb3d25f4d52f2a',
    weight: '0',
    tag: '09d4064fff666667ef9b64c9abcdec02',
    name: '视频转码',
    enter: '',
    isnav: '0',
    is_pc_nav: '1',
    version: '1.0.0',
    isphone: '0',
    baseurl: 'http://upload.shandian.design',
    indexfunc: '',
    download: '',
    scheme: 'sdy_uploads',
    icon: 'https://shandianyun.iqilu.com/home-logo/sdy_uploads.png',
    color: null,
    quick: [],
    opentype: '1',
    open_url: null,
    pc_weight: '11',
  },
  {
    id: '16',
    aeskey: '87c8715c522954bd4beb3d25f4d52f2a',
    weight: '6',
    tag: '786ac87bc12629e76b1deef5fa9665ee',
    name: '报纸',
    enter: 'toPaperList',
    isnav: '1',
    is_pc_nav: '1',
    version: '2.0.10',
    isphone: '1',
    baseurl: 'http://newspaper.shandian.design',
    indexfunc: '',
    download:
      'http://fugui.shandian.design//public/2020/09/23/489c1d5b3b49a65be09fbd15ed024f8a.zip',
    scheme: 'newspaper',
    icon: 'https://shandianyun.iqilu.com/home-logo/newspaper.png',
    color: 'null',
    quick: null,
    opentype: '1',
    open_url: 'null',
    pc_weight: '1000',
  },
  {
    id: '17',
    aeskey: '87c8715c522954bd4beb3d25f4d52f2a',
    weight: '0',
    tag: 'e841681cc83fd66c41f6c9534db16f22',
    name: '考核',
    enter: '',
    isnav: '0',
    is_pc_nav: '1',
    version: '2.0.5',
    isphone: '1',
    baseurl: 'http://audit.shandian.design',
    indexfunc: 'index',
    download:
      'http://fugui.shandian.design//public/2020/08/27/084814f5de2306dc3071107df70ab028.zip',
    scheme: 'audit',
    icon: 'https://shandianyun.iqilu.com/home-logo/audit.png',
    color: 'null',
    quick: [],
    opentype: '1',
    open_url: 'null',
    pc_weight: '1000',
  },
  {
    id: '20',
    aeskey: '87c8715c522954bd4beb3d25f4d52f2a',
    weight: '0',
    tag: 'b694a1d24f81f080486489eb90de2',
    name: 'TVU预约',
    enter: 'null',
    isnav: '0',
    is_pc_nav: '1',
    version: '1.0.0',
    isphone: '0',
    baseurl: 'http://backpack.shandian.design',
    indexfunc: 'null',
    download: 'null',
    scheme: 'backpack',
    icon: 'https://shandianyun.iqilu.com/home-logo/backpack.png',
    color: null,
    quick: [],
    opentype: '1',
    open_url: null,
    pc_weight: '1000',
  },
  {
    id: '21',
    aeskey: '87c8715c522954bd4beb3d25f4d52f2a',
    weight: '0',
    tag: 'b694a1d24f81f080486489eb90de3',
    name: '云培训',
    enter: 'null',
    isnav: '0',
    is_pc_nav: '1',
    version: '1.1.6',
    isphone: '1',
    baseurl: 'http://live.shandian.design',
    indexfunc: 'index',
    download:
      'http://fugui.shandian.design//public/2020/10/15/c6c0e8fae395fc8034ce11c3dc8954ea.zip',
    scheme: 'live',
    icon: 'https://shandianyun.iqilu.com/home-logo/live.png',
    color: 'null',
    quick: [],
    opentype: '1',
    open_url: 'null',
    pc_weight: '1000',
  },
  {
    id: '22',
    aeskey: '87c8715c522954bd4beb3d25f4d52f2a',
    weight: '0',
    tag: 'b694a1d24f81f080486489eb90de4',
    name: '数据统计',
    enter: 'null',
    isnav: '0',
    is_pc_nav: '1',
    version: '1.0.0',
    isphone: '0',
    baseurl: 'http://statistic.shandian.design',
    indexfunc: 'index',
    download: 'null',
    scheme: 'statistic',
    icon: 'https://shandianyun.iqilu.com/home-logo/statistic.png',
    color: null,
    quick: [],
    opentype: '1',
    open_url: null,
    pc_weight: '1000',
  },
  {
    id: '23',
    aeskey: '',
    weight: '0',
    tag: 'b694a1d24f81f080486489eb91wq4',
    name: '可视化编辑',
    enter: null,
    isnav: '0',
    is_pc_nav: '1',
    version: '',
    isphone: '0',
    baseurl: '',
    indexfunc: null,
    download: '',
    scheme: 'keshihuabianji',
    icon: 'https://shandianyun.iqilu.com/home-logo/keshihuabianji.png',
    color: null,
    quick: [],
    opentype: '3',
    open_url: null,
    pc_weight: '1000',
  },
  {
    id: '24',
    aeskey: '',
    weight: '0',
    tag: 'b694a1d24f81f459186489eb91wq4',
    name: 'H5',
    enter: null,
    isnav: '0',
    is_pc_nav: '1',
    version: '',
    isphone: '0',
    baseurl: '',
    indexfunc: null,
    download: '',
    scheme: 'h5',
    icon: 'https://shandianyun.iqilu.com/home-logo/h5.png',
    color: null,
    quick: [],
    opentype: '2',
    open_url: 'http://ipage.qiludev.com/auth/login',
    pc_weight: '1000',
  },
  {
    id: '25',
    aeskey: '',
    weight: '0',
    tag: 'b69479344f81f459186489eb91wq4',
    name: '视频剪辑',
    enter: null,
    isnav: '0',
    is_pc_nav: '1',
    version: '',
    isphone: '0',
    baseurl: '',
    indexfunc: null,
    download: '',
    scheme: 'shipinjianji',
    icon: 'https://shandianyun.iqilu.com/home-logo/shipinjianji.png',
    color: null,
    quick: [],
    opentype: '1',
    open_url: null,
    pc_weight: '1000',
  },
  {
    id: '26',
    aeskey: '',
    weight: '0',
    tag: 'b69479344f81f459186489ewaq159',
    name: '舆情分析',
    enter: null,
    isnav: '0',
    is_pc_nav: '1',
    version: '',
    isphone: '0',
    baseurl: '',
    indexfunc: null,
    download: '',
    scheme: 'public_sentiment',
    icon: 'https://shandianyun.iqilu.com/home-logo/public_sentiment.png',
    color: null,
    quick: [],
    opentype: '2',
    open_url: 'https://u1.gsdata.cn/member/login?url=http://yuqing.gsdata.cn/vindex/yuYingGather',
    pc_weight: '1000',
  },
  {
    id: '28',
    aeskey: '87c8715c522954bd4beb3d25f4d52f2a',
    weight: '0',
    tag: 'b694a1d24f81f080486489eb90de6',
    name: '串联单展示',
    enter: 'null',
    isnav: '0',
    is_pc_nav: '1',
    version: '1.0.0',
    isphone: '0',
    baseurl: 'http://show.shandian.design',
    indexfunc: 'index',
    download: 'null',
    scheme: 'show',
    icon: 'https://user.shandian.design/home-logo/chuan-lian-dan.png',
    color: null,
    quick: [],
    opentype: '1',
    open_url: null,
    pc_weight: '1000',
  },
  {
    id: '30',
    aeskey: '',
    weight: '0',
    tag: 'b69479344f81f459186489eb91wq4',
    name: '一县一端',
    enter: null,
    isnav: '0',
    is_pc_nav: '1',
    version: '',
    isphone: '0',
    baseurl: '',
    indexfunc: null,
    download: '',
    scheme: 'chuangqi',
    icon: 'https://user.shandian.design/home-logo/chuang-qi.png',
    color: null,
    quick: [],
    opentype: '4',
    open_url: null,
    pc_weight: '1000',
  },
];
